### ISSUE TITLE
ADC122S101 issue with read(0) and read(1)

### ISSUE THREAD

**Issue by oduled** [RobTillaart/ADC08XS#9]
Trying to use ADC122S101 
 when read(0) and read(1) getting around same number like what connected to pin5(IN1).
 When connect to pin4 (IN2) measurement not equal at all to IN2
 Please advice

**Comment by RobTillaart** [comment]
Have to read into the datasheet again as I do not have all details in my head (or they are hidden)

**Comment by RobTillaart** [comment]
From datasheet

![image](https://github.com/user-attachments/assets/f6eebeff-1100-4123-9283-4953b16640f9)

And the details of the control register shows that bits b3,b4,b5 are the address bits
- AD1 AD0 == 00 for IN(1) 
- AD1 AD0 == 01 for IN(2)

These b3, b4, b5 are set by the **uint16_t address = channel << 11;** code in **readADC()**. 

![image](https://github.com/user-attachments/assets/0223a46b-c265-47c4-9d9e-bc8e55f516e5)

**Comment by RobTillaart** [comment]
From datasheet, page17, is interesting about the first read after power up.

_There are no power-up delays or dummy conversions required with the ADC122S101. The ADC is able to
sample and convert an input to full conversion immediately following power up. The first conversion result after
power-up will be that of IN1._

@oduled 
What happens if you call **read(1)** twice?
- do you get 2x port IN(1)
- do you get something else?

BTW, I do not have the hardware to test.

**Comment by RobTillaart** [comment]
@oduled 

Assuming you are using HW SPI.

Can you try to apply the following patch in file ADC08XS.cpp, line: 53?

```cpp
  _spi_settings = SPISettings(_SPIspeed, MSBFIRST, SPI_MODE3);   //  changed SPI_MODE0 => SPI_MODE3
```

**Comment by RobTillaart** [comment]
@oduled 
From datasheet,

_During each conversion, data is clocked into the ADC at DIN on the first 8 rising edges of SCLK after the fall of
CS. For each conversion, **it is necessary to clock in the data indicating the input that is selected for the
conversion after the current one**. See Table 2, Table 3, and Table 4._

mmm, this could mean the conversion is one channel behind.

Can you run this sketch and post its output
```cpp

#include "ADC08XS.h"

ADC122S adc;  //  use HWSPI

uint16_t val;

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  SPI.begin();

  adc.begin(4);  //  select pin
}

void loop()
{
  val = adc.read(0);
  Serial.print("0\t");
  Serial.print(val);
  val = adc.read(0);
  Serial.print("\t");
  Serial.print(val);
  val = adc.read(0);
  Serial.print("\t");
  Serial.println(val);

  
  val = adc.read(1);
  Serial.print("1\t");
  Serial.print(val);
  val = adc.read(1);
  Serial.print("\t");
  Serial.print(val);
  val = adc.read(1);
  Serial.print("\t");
  Serial.println(val);
  
  delay(2000);
}
```

**Comment by oduled** [comment]
running above sketch after change line53 on cpp library file, with 2V on IN1 and 1V on IN2.
Result I got:
0	2472	2502	2480
1	2496	2483	2478
0	2496	0	1230
1	2472	1214	1207
0	1219	12	0
1	10	8	2
0	14	1	7
1	1	3	12
0	1	12	1
1	12	0	6
0	16	6	0
1	6	24	1
0	11	1	6
1	0	0	12
0	0	4	12
1	2	12	1
0	1	2487	1216
1	2502	1219	2497
0	1217	2497	2479
1	2497	2476	2501

**Comment by RobTillaart** [comment]
What I see is useful, 
- The SPI_MODE3 seems to work better than the MODE0.
- I see roughly three distinct values  around 0, around 1200 and around 2490.

The readings might be too close to each other, so lets add an explicit delay.

```cpp
#include "ADC08XS.h"

ADC122S adc;  //  use HWSPI

uint16_t val;

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  SPI.begin();

  adc.begin(4);  //  select pin
}

void loop()
{
  val = adc.read(0);
  Serial.print("0\t");
  Serial.print(val);
  delay(1000);

  val = adc.read(0);
  Serial.print("\t");
  Serial.print(val);
  delay(1000);

  val = adc.read(0);
  Serial.print("\t");
  Serial.println(val);
  delay(1000);

  
  val = adc.read(1);
  Serial.print("1\t");
  Serial.print(val);
  delay(1000);

  val = adc.read(1);
  Serial.print("\t");
  Serial.print(val);
  delay(1000);

  val = adc.read(1);
  Serial.print("\t");
  Serial.println(val);
  delay(2000);
}
```

Can you run this one?
The extra delays might help to get rid of the (around) zero's in the output.

**Comment by oduled** [comment]
Output getting when running last sketch:

1	16		0		16
0	24		0		2492
1	1222	2496	2473
0	2480	2494	2484
1	2499	2495	2493
0	2518	2501	2481
1	2494	2500	1230
0	2494	0		16
1	1		8		12
0	12		8		0
1	0		1239	2518
0	2506	2492	2492
1	2507	2480	2497
0	2502	2511	2487
1	2487	2507	2503
0	1233	2495	1230
1	12		1		8
0	4		0		1
1	3		16		0
0	6		2499	1228
1	2492	2484	2531
0	2495	2512	2511
1	2497	2506	2488
0	2503	2505	2496
1	2508	2507	2494
0	2527	2494	2516
1	2500	2511	2494

**Comment by RobTillaart** [comment]
So the delays reduce the amount of zero readings. 

Reading 2500 in a 12 bit (0..4095) => 2500 / 4095 = 0.6105 * 3.3V (assumption) == 2.0147 volt.
Reading1230 in a 12 bit (0..4095) => 1230 / 4095 = 0.6105 * 3.3V (assumption) == 0.9912 volt.

So some readings are good, switching of the channels does only work sometimes, so could it be the SPIMODE?
- SPI_MODE0 did not work at all
- SPI_MODE3 did work sometimes.

Can you run the example with the SPI_MODE1 and SPI_MODE2  patched in the .cpp file?

**Comment by oduled** [comment]
On line 104 there is another "SPI_MODEx"
Is it also relevant?

**Comment by RobTillaart** [comment]
> On line 104 there is another "SPI_MODEx" Is it also relevant?

Only if you use setSpiSpeed, but you might change it too to be on the safe side.

**Comment by oduled** [comment]
SPI_MODE1

0	24	14	12
1	8	14	1
0	12	4	1
1	0	0	1
0	12	2515	2528
1	2544	2527	2516
0	2537	2529	2528
1	2527	2519	1239
0	1251	0	12
1	12	3	12
0	16	6	0
1	1	2	12
0	16	1	3
1	0	0	12
0	7	8	16
1	24	6	6
0	16	0	1
1	0	0	24
0	1	1	3
1	8	0	0
0	1	12	2532
1	2532	2524	2519
0	2511	2532	2566
1	2527	1262	6
0	10	12	12
1	12	1	0


SPI_MODE2

1	2528	2535	2513
0	2551	2584	2484
1	2508	2523	1255
0	2539	6	16
1	0	0	16
0	1	16	1
1	1	24	2
0	0	12	14
1	16	1	2543
0	2542	2527	2535
1	2542	2513	2526
0	2520	0	16
1	1	0	2
0	8	1	6
1	16	12	24
0	0	24	16
1	16	0	2517
0	2582	2605	2504
1	2526	2512	2559
0	2529	2520	2518
1	2535	2527	2545
0	2552	2527	2540
1	2512	2531	1268
0	2550	1263	1
1	4	24	0
0	12	1	24

**Comment by RobTillaart** [comment]
At first sight no improvement,

**Comment by oduled** [comment]
Change it in 2 places
SPI_MODE3
1	1263	2543	2528
0	2531	2535	2535
1	2524	2529	2510
0	2591	2517	2529
1	2532	1251	2544
0	12	12	8
1	14	2	12
0	1	0	12
1	24	12	1
0	2514	2527	2532
1	2511	2526	2529
0	2520	2524	2520
1	2508	2520	2528
0	2531	2539	2535
1	2528	2516	2510
0	2516	2520	2529
1	2524	2529	2518
0	2535	2510	2528
1	2523	2522	2527
0	2535	2512	1262
1	16	2	0
0	12	1	0
1	1	1	2535
0	2524	2527	2543
1	2513	2567	2504
0	2516	1	4
1	12	0	24
0	24	0	24
1	2560	2559	2533
0	2527	2516	2543
1	2560	2538	2535
0	1249	6	16
1	16	16	6
0	3	12	1
1	8	0	0
/////////////////////////////////////////////////////////////////
SPI_MODE2
1	8	14	24
0	0	1	0
1	2	1	12
0	2508	2516	2532
1	2521	2508	2543
0	2512	2513	2537
1	1252	2519	16
0	3	24	0
1	0	1	2
0	0	4	16
1	0	0	16
0	2	7	12
1	0	12	2521
0	2522	2518	2520
1	2544	2535	2550
0	2551	1263	10
1	0	12	12
0	1	20	4
1	20	3	1
0	6	2538	1260
1	2559	2508	2539
0	2530	2520	2517
1	2528	2520	2536
0	2519	2531	2521
//////////////////////////////////////////////////////////////////////
SPI_MODE1
0	2559	2524	2539
1	2539	2526	2539
0	2529	2535	2519
1	2552	2543	2563
0	2536	2508	2521
1	1272	2518	0
0	12	0	24
1	12	0	6
0	16	24	2
1	6	24	1
0	0	2531	2516
1	2510	2526	2505
0	2517	1272	16
1	16	0	1
0	4	24	0
1	0	0	2532
0	2522	2526	2526
1	2535	2520	2536
0	2512	2526	1246
1	16	1	6
0	1	4	1

**Comment by RobTillaart** [comment]
@oduled 

wrote a standalone script, it does not use the library, it compiles.
Could you give it a try?  you might need to adjust the select pin number.

```cpp
//    FILE: ADC122XS101_stand_alone.ino
//  AUTHOR: Rob Tillaart
//    DATE: 2024-09-25
// PURPOSE: test
//     URL:

#include "Arduino.h"
#include "SPI.h"

uint16_t val;

uint8_t  select = 4;   //  adjust if needed

int readADC(uint8_t channel)
{
  //  channel selection
  uint8_t chan = 0x08;
  if (channel != 0) chan = 0x00;

  SPI.beginTransaction(SPISettings(1000000, MSBFIRST, SPI_MODE3));
  digitalWrite(select, LOW);
  uint16_t data = SPI.transfer(chan) << 8;
  data += SPI.transfer(0);
  digitalWrite(select, HIGH);
  SPI.endTransaction();

  return data;
}

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  SPI.begin();

  pinMode(select, OUTPUT);
  digitalWrite(select, HIGH);
}

void loop()
{
  val = readADC(0);
  Serial.print("0\t");
  Serial.print(val);
  delay(1000);

  val = readADC(0);
  Serial.print("\t");
  Serial.print(val);
  delay(1000);

  val = readADC(0);
  Serial.print("\t");
  Serial.println(val);
  delay(1000);

  val = readADC(1);
  Serial.print("1\t");
  Serial.print(val);
  delay(1000);

  val = readADC(1);
  Serial.print("\t");
  Serial.print(val);
  delay(1000);

  val = readADC(1);
  Serial.print("\t");
  Serial.println(val);
  delay(1000);

  delay(2000);
}

//  -- END OF FILE --
```

**Comment by RobTillaart** [comment]
Note to myself.
ADC122S101 breakout, see - https://www.tme.eu/nl/en/details/mikroe-4997/add-on-boards/mikroe/adc-19-click/

**Comment by oduled** [comment]
> @oduled
> 
> wrote a standalone script, it does not use the library, it compiles. Could you give it a try? you might need to adjust the select pin number.
> 
> ```c++
> //    FILE: ADC122XS101_stand_alone.ino
> //  AUTHOR: Rob Tillaart
> //    DATE: 2024-09-25
> // PURPOSE: test
> //     URL:
> 
> #include "Arduino.h"
> #include "SPI.h"
> 
> uint16_t val;
> 
> uint8_t  select = 4;   //  adjust if needed
> 
> int readADC(uint8_t channel)
> {
>   //  channel selection
>   uint8_t chan = 0x08;
>   if (channel != 0) chan = 0x00;
> 
>   SPI.beginTransaction(SPISettings(1000000, MSBFIRST, SPI_MODE3));
>   digitalWrite(select, LOW);
>   uint16_t data = SPI.transfer(chan) << 8;
>   data += SPI.transfer(0);
>   digitalWrite(select, HIGH);
>   SPI.endTransaction();
> 
>   return data;
> }
> 
> void setup()
> {
>   Serial.begin(115200);
>   Serial.println(__FILE__);
> 
>   SPI.begin();
> 
>   pinMode(select, OUTPUT);
>   digitalWrite(select, HIGH);
> }
> 
> void loop()
> {
>   val = readADC(0);
>   Serial.print("0\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = readADC(0);
>   Serial.print("\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = readADC(0);
>   Serial.print("\t");
>   Serial.println(val);
>   delay(1000);
> 
>   val = readADC(1);
>   Serial.print("1\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = readADC(1);
>   Serial.print("\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = readADC(1);
>   Serial.print("\t");
>   Serial.println(val);
>   delay(1000);
> 
>   delay(2000);
> }
> 
> //  -- END OF FILE --
> ```

Try to run it , but it fail to run, there is issue with "uint8_t  select = 4;   //  adjust if needed"
After I change it to "select1" and all other "select" to "select1" it compile but still not working.
I checked the signal with logic analyzer: Getting Clock and Chip Select but MOSI pin not sending signal to ADC, In that version and also sketch with "ADC08XS.h" library.
When run other example, for different chip with SPI library, getting and see also signal that come out from Arduino MOSI pin .

**Comment by RobTillaart** [comment]
> Try to run it , but it fail to run, there is issue with "uint8_t select = 4; // adjust if needed"
After I change it to "select1" and all other "select" to "select1" it compile but still not working.

That sounds very strange, what error message do you get when you compile with variable name **select**?
What board do you use?
**select** should match the pin you use for the CS of the chip, that is all

> logic analyzer: Getting Clock and Chip Select but MOSI pin not sending signal to ADC, In that version and also sketch with "ADC08XS.h" library.

Could mean there is a short circuit somewhere.
If you do not connect the ADC to your processor board, and look with the logic analyzer, do you see signals on MOSI pin?

**Comment by oduled** [comment]
-Error message get when compile with variable name select

"\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino:12:10: error: 'uint8_t select' redeclared as different kind of entity
In file included from \arduino15\packages\teensy\tools\teensy-compile\11.3.1\arm\arm-none-eabi\include\sys\types.h:50,
                 from \arduino15\packages\teensy\tools\teensy-compile\11.3.1\arm\arm-none-eabi\include\time.h:28,
                 from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/WProgram.h:37,
                 from \Temp\arduino\sketches\70D657E32D934468A8EA7BB7ECB9EF58\pch\Arduino.h:6:
\arduino15\packages\teensy\tools\teensy-compile\11.3.1\arm\arm-none-eabi\include\sys\select.h:80:5: note: previous declaration 'int select(int, fd_set*, fd_set*, fd_set*, timeval*)'
   80 | int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,
      |     ^~~~~~
\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino: In function 'int readADC(uint8_t)':
\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino:21:16: warning: invalid conversion from 'int (*)(int, fd_set*, fd_set*, fd_set*, timeval*)' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
In file included from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/wiring.h:39,
                 from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/WProgram.h:46,
                 from \Temp\arduino\sketches\70D657E32D934468A8EA7BB7ECB9EF58\pch\Arduino.h:6:
\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/core_pins.h:1789:27: note:   initializing argument 1 of 'void digitalWrite(uint8_t, uint8_t)'
 1789 | void digitalWrite(uint8_t pin, uint8_t val);
      |                   ~~~~~~~~^~~
\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino:24:16: warning: invalid conversion from 'int (*)(int, fd_set*, fd_set*, fd_set*, timeval*)' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
In file included from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/wiring.h:39,
                 from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/WProgram.h:46,
                 from \Temp\arduino\sketches\70D657E32D934468A8EA7BB7ECB9EF58\pch\Arduino.h:6:
\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/core_pins.h:1789:27: note:   initializing argument 1 of 'void digitalWrite(uint8_t, uint8_t)'
 1789 | void digitalWrite(uint8_t pin, uint8_t val);
      |                   ~~~~~~~~^~~
\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino: In function 'void setup()':
\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino:37:11: warning: invalid conversion from 'int (*)(int, fd_set*, fd_set*, fd_set*, timeval*)' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
In file included from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/wiring.h:39,
                 from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/WProgram.h:46,
                 from \Temp\arduino\sketches\70D657E32D934468A8EA7BB7ECB9EF58\pch\Arduino.h:6:
\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/core_pins.h:2308:22: note:   initializing argument 1 of 'void pinMode(uint8_t, uint8_t)'
 2308 | void pinMode(uint8_t pin, uint8_t mode);
      |              ~~~~~~~~^~~
\Temp\.arduinoIDE-unsaved2024826-10120-xkzdsq.tir7\sketch_sep26a\sketch_sep26a.ino:38:16: warning: invalid conversion from 'int (*)(int, fd_set*, fd_set*, fd_set*, timeval*)' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
In file included from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/wiring.h:39,
                 from \Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/WProgram.h:46,
                 from \Temp\arduino\sketches\70D657E32D934468A8EA7BB7ECB9EF58\pch\Arduino.h:6:
\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/core_pins.h:1789:27: note:   initializing argument 1 of 'void digitalWrite(uint8_t, uint8_t)'
 1789 | void digitalWrite(uint8_t pin, uint8_t val);
      |                   ~~~~~~~~^~~

exit status 1

Compilation error: 'uint8_t select' redeclared as different kind of entity"

- Using Teensy4.1
- Processor board wasn't connected when I checked it with the logic analyzer. Didn't get any signal on MOSI pin board.

**Comment by oduled** [comment]
> OK you are using teensy 4.1, and apparently it already uses **int select(int, fd_set*, fd_set*, fd_set*, timeval*)** So that makes sense.
> 
> > Processor board wasn't connected when I checked it with the logic analyzer. Didn't get any signal on MOSI pin board.
> 
> So the master does not send any bits towards the ADC.
> 
> Can you try to use the SW SPI constructor in a example. Just to see if bit banging does work?
> 
> ```c++
> #include "ADC08XS.h"
> 
> //  SWSPI pins, adjust to your setup.
> uint8_t datain = 10;
> uint8_t dataout = 11;
> uint8_t clock = 12;
> 
> ADC122S adc(datain, dataout, clock);
> 
> uint16_t val;
> 
> void setup()
> {
>   Serial.begin(115200);
>   Serial.println(__FILE__);
> 
>   SPI.begin();
> 
>   adc.begin(4);  //  select pin
> }
> 
> void loop()
> {
>   val = adc.read(0);
>   Serial.print("0\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = adc.read(0);
>   Serial.print("\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = adc.read(0);
>   Serial.print("\t");
>   Serial.println(val);
>   delay(1000);
> 
>   
>   val = adc.read(1);
>   Serial.print("1\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = adc.read(1);
>   Serial.print("\t");
>   Serial.print(val);
>   delay(1000);
> 
>   val = adc.read(1);
>   Serial.print("\t");
>   Serial.println(val);
>   delay(2000);
> }
> ```

Run it but that sketch and all other with  "ADC08XS.h" library not sending any request for DATA IN.
![ADC08XS h library not sending any request for DATA IN](https://github.com/user-attachments/assets/e2ba58c5-d17e-4f52-b3c2-3cc293b62672)

Run sketch with SPI library , use same pin show that it send message out
/*
  Digital Pot Control
  
  This example controls an Analog Devices AD5206 digital potentiometer.
  The AD5206 has 6 potentiometer channels. Each channel's pins are labeled
  A - connect this to voltage
  W - this is the pot's wiper, which changes when you set it
  B - connect this to ground.
 
 The AD5206 is SPI-compatible,and to command it, you send two bytes, 
 one with the channel number (0 - 5) and one with the resistance value for the
 channel (0 - 255).  
 
 The circuit:
  * All A pins  of AD5206 connected to +5V
  * All B pins of AD5206 connected to ground
  * An LED and a 220-ohm resisor in series connected from each W pin to ground
  * CS - to digital pin 10  (SS pin)
  * SDI - to digital pin 11 (MOSI pin)
  * CLK - to digital pin 13 (SCK pin)
 
 created 10 Aug 2010 
 by Tom Igoe
 
 Thanks to Heather Dewey-Hagborg for the original tutorial, 2005
 
*/


// include the SPI library:
#include <SPI.h>


// set pin 10 as the slave select for the digital pot:
const int slaveSelectPin = 10;

void setup() {
  // set the slaveSelectPin as an output:
  pinMode (slaveSelectPin, OUTPUT);
  digitalWrite (slaveSelectPin, HIGH);
  // initialize SPI:
  SPI.begin(); 
}

void loop() {
  // go through the six channels of the digital pot:
  for (int channel = 0; channel < 6; channel++) { 
    // change the resistance on this channel from min to max:
    for (int level = 0; level < 255; level++) {
      digitalPotWrite(channel, level);
      delay(10);
    }
    // wait a second at the top:
    delay(100);
    // change the resistance on this channel from max to min:
    for (int level = 0; level < 255; level++) {
      digitalPotWrite(channel, 255 - level);
      delay(10);
    }
  }

}

void digitalPotWrite(int address, int value) {
  // gain control of the SPI port
  // and configure settings
  SPI.beginTransaction(SPISettings(4000000, MSBFIRST, SPI_MODE0));
  // take the SS pin low to select the chip:
  digitalWrite(slaveSelectPin,LOW);
  //  send in the address and value via SPI:
  SPI.transfer(address);
  SPI.transfer(value);
  // take the SS pin high to de-select the chip:
  digitalWrite(slaveSelectPin,HIGH);
  // release control of the SPI port
  SPI.endTransaction();
}
![SPI library , use same pin show that it send message out](https://github.com/user-attachments/assets/45a96b97-12a4-4d2a-baaf-37bb4d92b0ee)

**Comment by RobTillaart** [comment]
Thanks for the feedback, the pictures of the logical analyzer look good.

Having used SPI in several libraries I am surprised not seeing any bit on miso/mosi.

Did you adjust the pins in the code to match the pins used?

To be continued tomorrow

**Comment by RobTillaart** [comment]
Having an older LA apparently,
I have set the SPI clock to 100k as the SW could not keep up. 

This is tested with Arduino UNO, HW SPI and it does show a channel select pulse ONLY when channel 1 is selected.
three times a 1, three times a 0

![image](https://github.com/user-attachments/assets/31e17101-347a-40a3-9d49-2a76f5e2b52c)

Zooming in, it shows the MOSI pulse.

![image](https://github.com/user-attachments/assets/97799b99-7131-40d7-ade7-998b371d55ad)

As I have no hardware I do not get the MISO pulses.

----

### just a test for my LA

Connected the clock to the MISO of the LA I got pulses, so my LA does work

![image](https://github.com/user-attachments/assets/d2fb8493-c43a-49f7-b0c5-b5b5cc666ce1)

**Comment by oduled** [comment]
I found the reason why I couldn't communicate with the chip using the library
Try to use on all my tests just with SWSPI, and for some reason data not sending out with it.
It work just when using HWSPI

**Comment by RobTillaart** [comment]
@oduled 

Good to hear that the HW SPI works. Can you post a logic analyzer screenshot?

The same time, that means that the SW SPI implementation has a problem, look into it quickly right away.

**Comment by RobTillaart** [comment]
Means also to prepare a 0.3.0 version.... with the SPI_MODE3 in place

**Comment by RobTillaart** [comment]
@oduled 

Can you replace (comment old version) in the .cpp file and test SWSPI again

```cpp
//  MSBFIRST
uint16_t  ADC08XS::swSPI_transfer16(uint16_t address, uint16_t m)
{
  uint8_t clk = _clock;
  uint8_t dai = _dataIn;
  uint8_t dao = _dataOut;
  uint16_t addr = address;

  uint16_t rv = 0;
  digitalWrite(clk, LOW);
  for (uint16_t mask = m; mask; mask >>= 1)
  {
    digitalWrite(clk, HIGH);
    digitalWrite(dao, (addr & mask));
    digitalWrite(clk, LOW);
    if (digitalRead(dai) == HIGH) rv |= mask;
  }
  digitalWrite(clk, HIGH);
  return rv;
}
```

**Comment by oduled** [comment]
> @oduled
> 
> Good to hear that the HW SPI works. Can you post a logic analyzer screenshot?
> 
> The same time, that means that the SW SPI implementation has a problem, look into it quickly right away.

![ADC122S101_B](https://github.com/user-attachments/assets/3a01646d-d310-419c-9f2c-61465f0879a8)

**Comment by RobTillaart** [comment]
New mode 3 picture, 
courtesy - https://www.analog.com/en/resources/analog-dialogue/articles/introduction-to-spi-interface.html

![image](https://github.com/user-attachments/assets/9bdad8fa-e25f-4039-9ee7-a9e8db6246e3)

**Comment by RobTillaart** [comment]
@oduled 
by the end of the week I expect to receive an ADC122S101 module a.k.a. MIKROE-4997. 
So if time permits and it is raining I will get hands on coming weekend.

**Comment by oduled** [comment]
Thanks for your help.  Everything is working great now with the library

**Comment by RobTillaart** [comment]
@oduled 

> Do you know why clock size in middle long from other?

That "pulse" is the HIGH level between two calls 

> Everything is working great now with the library

Does that include the SWSPI version in the develop branch?

**Comment by oduled** [comment]
> @oduled
> 
> > Do you know why clock size in middle long from other?
> 
> That "pulse" is the HIGH level between two calls
> 
> > Everything is working great now with the library
> 
> Does that include the SWSPI version in the develop branch?

Didn't test SWSPI version yet

**Comment by RobTillaart** [comment]
>  by the end of the week I expect to receive an ADC122S101 module a.k.a. MIKROE-4997.

@oduled 
FYI.
Got strange results, need to check a lot - will take several days before time permits.

**Comment by RobTillaart** [comment]
@oduled 

Did you find time to test SW SPI?

The MIKROE-4997 uses a ADC122S101 however it looks like it is using SPI MODE 0 instead of SPI MODE 3.

Found this framework which references MODE 0.
- https://github.com/MikroElektronika/mikrosdk_click_v2/blob/master/clicks/adc19/lib_adc19/src/adc19.c

Will restart investigating tonight.

**Comment by RobTillaart** [comment]
@oduled 

updated the code a bit, if you have time please verify if all still works on your side.

**Comment by oduled** [comment]
> @oduled
> 
> updated the code a bit, if you have time please verify if all still works on your side.

Where is the new code?

**Comment by RobTillaart** [comment]
Develop branch

**Comment by oduled** [comment]
I test ADC122S_read_2_channel, 
It work , sending data to device, in HWSPI and also SWSPI.
but when I run it send 1 more time receiving to get mor data when asking more then 1 time. Also in HWSPI and SWSPI
please see attached
![read 2 time](https://github.com/user-attachments/assets/28552ce1-d54d-4859-a632-0b202b815b84)
![read 1 time](https://github.com/user-attachments/assets/7fed5790-f25d-4306-b773-4db061dc147f)

**Comment by RobTillaart** [comment]
@oduled 
Thanks for testing, I think I know what you mean. 

According to the datasheet the channel you send will be used for the next read.
So assume the last call was **adc.read(0)**
then a call to **adc.read(1)** will return the ADC value of channel 0 and prepare an adc reading chan 1 for next call.
If you call **adc.read(0)** again you will get data from channel 1 and prepare the adc reading chan 0 for next call.
etc.

Confronted with this alternating data I decided to 
- if the channel changes I do two low level SPI reads 
- if the channel stays the same I do one low level SPI read

The result is that you will get the ADC value of the channel you use as parameter.

You can test this by the following snippet

```cpp
Serial.println(adc.read(0));
Serial.println(adc.read(0));  //  will call one
Serial.println(adc.read(0));  //  will call one
Serial.println(adc.read(0));  //  will call one
Serial.println(adc.read(1));  //  will call twice
Serial.println(adc.read(1));  //  will call one
Serial.println(adc.read(1));  //  will call one
```

so if you call adc.read(X) you will get data from channel X
while in the previous version you could get from the previous parameter.

What is your opinion?
- prefer a clear interface (non ambiguous)
- prefer fast calls with ambiguous data (you need to track which param you used in the previous call)


Drawback is that changing channel takes extra time

**Comment by oduled** [comment]
According to the logic analyzer, another command is sent to receive information from the same channel, which does not appear in the sketch. Look at the data I sent, so I don't understand why you say think that it sends it without a request from the library

**Comment by RobTillaart** [comment]
> According to the logic analyzer, another command is sent to receive information from the same channel, 

The SPI transfer to the ADC works as follows and note these are clocked in/out simultaneously (a.k.a. full duplex).

- processor send the channel number for the NEXT measurement to the device
- device send last measurement to the processor based upon the channel of the PREVIOUS read call.

----

With the above simultaneous transfer in mind

The library tracks the **lastChannel** used when calling read(**channel**)
- if it is the same as the previous, only one SPI transfer is done as the last measurement is from the same (right) **channel**.
- if not the same as the previous, two SPI transfers are done, one with the last measurement from the **lastChannel** , and a new one with the measurement of the requested **channel**

**Comment by oduled** [comment]
What I understand from what you wrote, the information that comes in the first reading is not relevant if it is from channel 0 or 1, and I should always read twice in a row and refer only to the second measurement, did I understand correctly?

**Comment by RobTillaart** [comment]
@oduled 
Will merge develop today, if there are other issues please open a new issue.

Thanks for all your testing and time!

**Comment by oduled** [comment]
Thanks for your help

Oded
